// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ServerResourcesDataAccess;

namespace ServerResourcesDataAccess.Migrations
{
    [DbContext(typeof(ServerResourcesContext))]
    [Migration("20191121111330_Initial_Migration")]
    partial class Initial_Migration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("ServerResourcesDataAccess.Sample_Time", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Time");

                    b.HasKey("Id");

                    b.ToTable("Sample_Time");
                });

            modelBuilder.Entity("ServerResourcesDataAccess.Server_Resource_Info", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Sample_Time_FK");

                    b.Property<int>("Server_Resource_Unit_FK");

                    b.Property<double>("Value");

                    b.HasKey("Id");

                    b.HasIndex("Sample_Time_FK");

                    b.HasIndex("Server_Resource_Unit_FK");

                    b.ToTable("Server_Resource_Info");
                });

            modelBuilder.Entity("ServerResourcesDataAccess.Server_Resource_Unit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ShortName")
                        .IsRequired();

                    b.Property<string>("Unit")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Server_Resource_Unit");
                });

            modelBuilder.Entity("ServerResourcesDataAccess.Test_Entity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Test_Entity");
                });

            modelBuilder.Entity("ServerResourcesDataAccess.Server_Resource_Info", b =>
                {
                    b.HasOne("ServerResourcesDataAccess.Sample_Time", "Sample_Time")
                        .WithMany("Computer_Resources")
                        .HasForeignKey("Sample_Time_FK")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ServerResourcesDataAccess.Server_Resource_Unit", "Server_Resource_Unit")
                        .WithMany("Computer_Resources")
                        .HasForeignKey("Server_Resource_Unit_FK")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
